name: Add release info on PR
on:
  release:
    types: [ published ]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
      - name: Add release information on pull requests
        uses: ./actions/post-release-info-onPullRequest
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: 'carbon-design-system'
          REPO_NAME: 'carbon'
          enabled: true
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
